
add_newline = false

[directory]
truncation_length = 3
style = "cyan"

[git_branch]
symbol = " "      # Nerd Font branch icon
style = "bold green"

[git_status]
format = "([$all_status$ahead_behind]($style))"
style = "bold yellow"
conflicted = "✖"
untracked = "??"
staged = "●"
modified = "✚"
renamed = "»"
deleted = "✘"
ahead = "↑"
behind = "↓"
stashed = "⚑"

[character]
symbol = "❯"
style = "bold blue"
error_symbol = "✖"
error_style = "bold red"

format = """
$directory$git_branch$git_status
$character """

