add_newline = false

[directory]
truncation_length = 3
style = "bold cyan"

[git_branch]
symbol = " "  # Nerd Font branch icon
style = "bold green"

[git_status]
format = "[$all_status]($style)"  
style = "bold yellow"
conflicted = "✖"      # conflicted changes
untracked = ""       # nerd font question mark
staged = "●"           # staged changes
modified = "✚"         # modified files
renamed = "»"          # renamed files
deleted = "✘"          # deleted files
ahead = "↑"
behind = "↓"
stashed = "⚑"

[character]
symbol = "❯"
style = "bold blue"
error_symbol = "✖"
error_style = "bold red"

# Final prompt layout
format = "$directory:$git_branch $git_status $character "

